### 1. Dummy Login (Admin) - ПОЛУЧАЕМ ТОКЕН
# @name adminLogin
POST http://localhost:8080/dummyLogin
Content-Type: application/json

{ "role": "admin" }

> {%
    client.global.set("adminToken", response.body.token);
    client.log("Admin Token saved!");
%}

### 2. Create Room (Admin) - ПОЛУЧАЕМ ID КОМНАТЫ
# @name createRoom
POST http://localhost:8080/rooms/create
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "name": "Room {{$randomInt}}",
  "capacity": 10
}

> {%
    client.global.set("roomId", response.body.room.id);
    client.log("Room ID saved: " + response.body.room.id);
%}

### 3. Create Schedule (Admin) - СОЗДАЕМ СЛОТЫ
POST http://localhost:8080/rooms/{{roomId}}/schedule/create
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "daysOfWeek": [1, 2, 3, 4, 5],
  "startTime": "09:00",
  "endTime": "10:00"
}

### 4. Dummy Login (User) - ПОЛУЧАЕМ ТОКЕН ЮЗЕРА
# @name userLogin
POST http://localhost:8080/dummyLogin
Content-Type: application/json

{ "role": "user" }

> {%
    client.global.set("userToken", response.body.token);
%}

### 5. List Slots - ПОЛУЧАЕМ ID СЛОТА
# @name listSlots
GET http://localhost:8080/rooms/{{roomId}}/slots/list?date=2026-04-10
Authorization: Bearer {{userToken}}

> {%
    client.global.set("slotId", response.body.slots[0].id);
    client.log("Slot ID saved: " + response.body.slots[0].id);
%}

### 6. Create Booking (User) - ФИНАЛЬНЫЙ ТЕСТ
POST http://localhost:8080/bookings
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "slotId": "{{slotId}}",
  "createConferenceLink": false
}