// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	model "MeetingRoomsAPI/internal/domain/model"
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockSlotRepository is an autogenerated mock type for the SlotRepository type
type MockSlotRepository struct {
	mock.Mock
}

type MockSlotRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSlotRepository) EXPECT() *MockSlotRepository_Expecter {
	return &MockSlotRepository_Expecter{mock: &_m.Mock}
}

// CreateBatch provides a mock function with given fields: ctx, slots
func (_m *MockSlotRepository) CreateBatch(ctx context.Context, slots []*model.Slot) error {
	ret := _m.Called(ctx, slots)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*model.Slot) error); ok {
		r0 = rf(ctx, slots)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSlotRepository_CreateBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBatch'
type MockSlotRepository_CreateBatch_Call struct {
	*mock.Call
}

// CreateBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - slots []*model.Slot
func (_e *MockSlotRepository_Expecter) CreateBatch(ctx interface{}, slots interface{}) *MockSlotRepository_CreateBatch_Call {
	return &MockSlotRepository_CreateBatch_Call{Call: _e.mock.On("CreateBatch", ctx, slots)}
}

func (_c *MockSlotRepository_CreateBatch_Call) Run(run func(ctx context.Context, slots []*model.Slot)) *MockSlotRepository_CreateBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*model.Slot))
	})
	return _c
}

func (_c *MockSlotRepository_CreateBatch_Call) Return(_a0 error) *MockSlotRepository_CreateBatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSlotRepository_CreateBatch_Call) RunAndReturn(run func(context.Context, []*model.Slot) error) *MockSlotRepository_CreateBatch_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockSlotRepository) Get(ctx context.Context, id uuid.UUID) (*model.Slot, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Slot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Slot, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Slot); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Slot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSlotRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockSlotRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockSlotRepository_Expecter) Get(ctx interface{}, id interface{}) *MockSlotRepository_Get_Call {
	return &MockSlotRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockSlotRepository_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockSlotRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSlotRepository_Get_Call) Return(_a0 *model.Slot, _a1 error) *MockSlotRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSlotRepository_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Slot, error)) *MockSlotRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ListFree provides a mock function with given fields: ctx, roomID, date
func (_m *MockSlotRepository) ListFree(ctx context.Context, roomID uuid.UUID, date time.Time) ([]*model.Slot, error) {
	ret := _m.Called(ctx, roomID, date)

	if len(ret) == 0 {
		panic("no return value specified for ListFree")
	}

	var r0 []*model.Slot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) ([]*model.Slot, error)); ok {
		return rf(ctx, roomID, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) []*model.Slot); ok {
		r0 = rf(ctx, roomID, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Slot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r1 = rf(ctx, roomID, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSlotRepository_ListFree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFree'
type MockSlotRepository_ListFree_Call struct {
	*mock.Call
}

// ListFree is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - date time.Time
func (_e *MockSlotRepository_Expecter) ListFree(ctx interface{}, roomID interface{}, date interface{}) *MockSlotRepository_ListFree_Call {
	return &MockSlotRepository_ListFree_Call{Call: _e.mock.On("ListFree", ctx, roomID, date)}
}

func (_c *MockSlotRepository_ListFree_Call) Run(run func(ctx context.Context, roomID uuid.UUID, date time.Time)) *MockSlotRepository_ListFree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockSlotRepository_ListFree_Call) Return(_a0 []*model.Slot, _a1 error) *MockSlotRepository_ListFree_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSlotRepository_ListFree_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) ([]*model.Slot, error)) *MockSlotRepository_ListFree_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSlotRepository creates a new instance of MockSlotRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSlotRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSlotRepository {
	mock := &MockSlotRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
