// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	model "MeetingRoomsAPI/internal/domain/model"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockScheduleRepository is an autogenerated mock type for the ScheduleRepository type
type MockScheduleRepository struct {
	mock.Mock
}

type MockScheduleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScheduleRepository) EXPECT() *MockScheduleRepository_Expecter {
	return &MockScheduleRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, schedule
func (_m *MockScheduleRepository) Create(ctx context.Context, schedule *model.Schedule) (*model.Schedule, error) {
	ret := _m.Called(ctx, schedule)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Schedule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Schedule) (*model.Schedule, error)); ok {
		return rf(ctx, schedule)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Schedule) *model.Schedule); ok {
		r0 = rf(ctx, schedule)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Schedule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Schedule) error); ok {
		r1 = rf(ctx, schedule)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockScheduleRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockScheduleRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - schedule *model.Schedule
func (_e *MockScheduleRepository_Expecter) Create(ctx interface{}, schedule interface{}) *MockScheduleRepository_Create_Call {
	return &MockScheduleRepository_Create_Call{Call: _e.mock.On("Create", ctx, schedule)}
}

func (_c *MockScheduleRepository_Create_Call) Run(run func(ctx context.Context, schedule *model.Schedule)) *MockScheduleRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Schedule))
	})
	return _c
}

func (_c *MockScheduleRepository_Create_Call) Return(_a0 *model.Schedule, _a1 error) *MockScheduleRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockScheduleRepository_Create_Call) RunAndReturn(run func(context.Context, *model.Schedule) (*model.Schedule, error)) *MockScheduleRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, roomID
func (_m *MockScheduleRepository) Get(ctx context.Context, roomID uuid.UUID) (*model.Schedule, error) {
	ret := _m.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Schedule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Schedule, error)); ok {
		return rf(ctx, roomID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Schedule); ok {
		r0 = rf(ctx, roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Schedule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockScheduleRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockScheduleRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
func (_e *MockScheduleRepository_Expecter) Get(ctx interface{}, roomID interface{}) *MockScheduleRepository_Get_Call {
	return &MockScheduleRepository_Get_Call{Call: _e.mock.On("Get", ctx, roomID)}
}

func (_c *MockScheduleRepository_Get_Call) Run(run func(ctx context.Context, roomID uuid.UUID)) *MockScheduleRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockScheduleRepository_Get_Call) Return(_a0 *model.Schedule, _a1 error) *MockScheduleRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockScheduleRepository_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Schedule, error)) *MockScheduleRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockScheduleRepository creates a new instance of MockScheduleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScheduleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScheduleRepository {
	mock := &MockScheduleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
