// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	model "MeetingRoomsAPI/internal/domain/model"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockBookingRepository is an autogenerated mock type for the BookingRepository type
type MockBookingRepository struct {
	mock.Mock
}

type MockBookingRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookingRepository) EXPECT() *MockBookingRepository_Expecter {
	return &MockBookingRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, booking
func (_m *MockBookingRepository) Create(ctx context.Context, booking *model.Booking) (*model.Booking, error) {
	ret := _m.Called(ctx, booking)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Booking) (*model.Booking, error)); ok {
		return rf(ctx, booking)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Booking) *model.Booking); ok {
		r0 = rf(ctx, booking)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Booking) error); ok {
		r1 = rf(ctx, booking)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBookingRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockBookingRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - booking *model.Booking
func (_e *MockBookingRepository_Expecter) Create(ctx interface{}, booking interface{}) *MockBookingRepository_Create_Call {
	return &MockBookingRepository_Create_Call{Call: _e.mock.On("Create", ctx, booking)}
}

func (_c *MockBookingRepository_Create_Call) Run(run func(ctx context.Context, booking *model.Booking)) *MockBookingRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Booking))
	})
	return _c
}

func (_c *MockBookingRepository_Create_Call) Return(_a0 *model.Booking, _a1 error) *MockBookingRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBookingRepository_Create_Call) RunAndReturn(run func(context.Context, *model.Booking) (*model.Booking, error)) *MockBookingRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockBookingRepository) Get(ctx context.Context, id uuid.UUID) (*model.Booking, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Booking, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Booking); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBookingRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockBookingRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockBookingRepository_Expecter) Get(ctx interface{}, id interface{}) *MockBookingRepository_Get_Call {
	return &MockBookingRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockBookingRepository_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockBookingRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockBookingRepository_Get_Call) Return(_a0 *model.Booking, _a1 error) *MockBookingRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBookingRepository_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Booking, error)) *MockBookingRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ListAll provides a mock function with given fields: ctx, limit, offset
func (_m *MockBookingRepository) ListAll(ctx context.Context, limit int32, offset int32) ([]*model.Booking, int64, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 []*model.Booking
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) ([]*model.Booking, int64, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) []*model.Booking); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, int32) int64); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int32, int32) error); ok {
		r2 = rf(ctx, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockBookingRepository_ListAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAll'
type MockBookingRepository_ListAll_Call struct {
	*mock.Call
}

// ListAll is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int32
//   - offset int32
func (_e *MockBookingRepository_Expecter) ListAll(ctx interface{}, limit interface{}, offset interface{}) *MockBookingRepository_ListAll_Call {
	return &MockBookingRepository_ListAll_Call{Call: _e.mock.On("ListAll", ctx, limit, offset)}
}

func (_c *MockBookingRepository_ListAll_Call) Run(run func(ctx context.Context, limit int32, offset int32)) *MockBookingRepository_ListAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(int32))
	})
	return _c
}

func (_c *MockBookingRepository_ListAll_Call) Return(_a0 []*model.Booking, _a1 int64, _a2 error) *MockBookingRepository_ListAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockBookingRepository_ListAll_Call) RunAndReturn(run func(context.Context, int32, int32) ([]*model.Booking, int64, error)) *MockBookingRepository_ListAll_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUserID provides a mock function with given fields: ctx, userID
func (_m *MockBookingRepository) ListByUserID(ctx context.Context, userID uuid.UUID) ([]*model.Booking, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 []*model.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*model.Booking, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*model.Booking); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBookingRepository_ListByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserID'
type MockBookingRepository_ListByUserID_Call struct {
	*mock.Call
}

// ListByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockBookingRepository_Expecter) ListByUserID(ctx interface{}, userID interface{}) *MockBookingRepository_ListByUserID_Call {
	return &MockBookingRepository_ListByUserID_Call{Call: _e.mock.On("ListByUserID", ctx, userID)}
}

func (_c *MockBookingRepository_ListByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockBookingRepository_ListByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockBookingRepository_ListByUserID_Call) Return(_a0 []*model.Booking, _a1 error) *MockBookingRepository_ListByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBookingRepository_ListByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*model.Booking, error)) *MockBookingRepository_ListByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, id, status
func (_m *MockBookingRepository) UpdateStatus(ctx context.Context, id uuid.UUID, status model.BookingStatus) error {
	ret := _m.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.BookingStatus) error); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBookingRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockBookingRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - status model.BookingStatus
func (_e *MockBookingRepository_Expecter) UpdateStatus(ctx interface{}, id interface{}, status interface{}) *MockBookingRepository_UpdateStatus_Call {
	return &MockBookingRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, status)}
}

func (_c *MockBookingRepository_UpdateStatus_Call) Run(run func(ctx context.Context, id uuid.UUID, status model.BookingStatus)) *MockBookingRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.BookingStatus))
	})
	return _c
}

func (_c *MockBookingRepository_UpdateStatus_Call) Return(_a0 error) *MockBookingRepository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBookingRepository_UpdateStatus_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.BookingStatus) error) *MockBookingRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBookingRepository creates a new instance of MockBookingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookingRepository {
	mock := &MockBookingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
