// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	"backend/internal/domain/model"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockRoomRepository is an autogenerated mock type for the RoomRepository type
type MockRoomRepository struct {
	mock.Mock
}

type MockRoomRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoomRepository) EXPECT() *MockRoomRepository_Expecter {
	return &MockRoomRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, room
func (_m *MockRoomRepository) Create(ctx context.Context, room *model.Room) (*model.Room, error) {
	ret := _m.Called(ctx, room)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Room) (*model.Room, error)); ok {
		return rf(ctx, room)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Room) *model.Room); ok {
		r0 = rf(ctx, room)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Room) error); ok {
		r1 = rf(ctx, room)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoomRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRoomRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - room *model.Room
func (_e *MockRoomRepository_Expecter) Create(ctx interface{}, room interface{}) *MockRoomRepository_Create_Call {
	return &MockRoomRepository_Create_Call{Call: _e.mock.On("Create", ctx, room)}
}

func (_c *MockRoomRepository_Create_Call) Run(run func(ctx context.Context, room *model.Room)) *MockRoomRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Room))
	})
	return _c
}

func (_c *MockRoomRepository_Create_Call) Return(_a0 *model.Room, _a1 error) *MockRoomRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoomRepository_Create_Call) RunAndReturn(run func(context.Context, *model.Room) (*model.Room, error)) *MockRoomRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockRoomRepository) Get(ctx context.Context, id uuid.UUID) (*model.Room, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Room, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Room); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoomRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRoomRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRoomRepository_Expecter) Get(ctx interface{}, id interface{}) *MockRoomRepository_Get_Call {
	return &MockRoomRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockRoomRepository_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRoomRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRoomRepository_Get_Call) Return(_a0 *model.Room, _a1 error) *MockRoomRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoomRepository_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Room, error)) *MockRoomRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockRoomRepository) List(ctx context.Context) ([]*model.Room, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*model.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*model.Room, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*model.Room); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoomRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRoomRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRoomRepository_Expecter) List(ctx interface{}) *MockRoomRepository_List_Call {
	return &MockRoomRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockRoomRepository_List_Call) Run(run func(ctx context.Context)) *MockRoomRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRoomRepository_List_Call) Return(_a0 []*model.Room, _a1 error) *MockRoomRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoomRepository_List_Call) RunAndReturn(run func(context.Context) ([]*model.Room, error)) *MockRoomRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRoomRepository creates a new instance of MockRoomRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoomRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoomRepository {
	mock := &MockRoomRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
