// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockConferenceService is an autogenerated mock type for the ConferenceService type
type MockConferenceService struct {
	mock.Mock
}

type MockConferenceService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConferenceService) EXPECT() *MockConferenceService_Expecter {
	return &MockConferenceService_Expecter{mock: &_m.Mock}
}

// CreateMeeting provides a mock function with given fields: _a0
func (_m *MockConferenceService) CreateMeeting(_a0 context.Context) (string, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CreateMeeting")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConferenceService_CreateMeeting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMeeting'
type MockConferenceService_CreateMeeting_Call struct {
	*mock.Call
}

// CreateMeeting is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockConferenceService_Expecter) CreateMeeting(_a0 interface{}) *MockConferenceService_CreateMeeting_Call {
	return &MockConferenceService_CreateMeeting_Call{Call: _e.mock.On("CreateMeeting", _a0)}
}

func (_c *MockConferenceService_CreateMeeting_Call) Run(run func(_a0 context.Context)) *MockConferenceService_CreateMeeting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockConferenceService_CreateMeeting_Call) Return(_a0 string, _a1 error) *MockConferenceService_CreateMeeting_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConferenceService_CreateMeeting_Call) RunAndReturn(run func(context.Context) (string, error)) *MockConferenceService_CreateMeeting_Call {
	_c.Call.Return(run)
	return _c
}

// SetMode provides a mock function with given fields: mode
func (_m *MockConferenceService) SetMode(mode string) {
	_m.Called(mode)
}

// MockConferenceService_SetMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMode'
type MockConferenceService_SetMode_Call struct {
	*mock.Call
}

// SetMode is a helper method to define mock.On call
//   - mode string
func (_e *MockConferenceService_Expecter) SetMode(mode interface{}) *MockConferenceService_SetMode_Call {
	return &MockConferenceService_SetMode_Call{Call: _e.mock.On("SetMode", mode)}
}

func (_c *MockConferenceService_SetMode_Call) Run(run func(mode string)) *MockConferenceService_SetMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockConferenceService_SetMode_Call) Return() *MockConferenceService_SetMode_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConferenceService_SetMode_Call) RunAndReturn(run func(string)) *MockConferenceService_SetMode_Call {
	_c.Run(run)
	return _c
}

// NewMockConferenceService creates a new instance of MockConferenceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConferenceService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConferenceService {
	mock := &MockConferenceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
