// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockTokenGenerator is an autogenerated mock type for the TokenGenerator type
type MockTokenGenerator struct {
	mock.Mock
}

type MockTokenGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenGenerator) EXPECT() *MockTokenGenerator_Expecter {
	return &MockTokenGenerator_Expecter{mock: &_m.Mock}
}

// GenerateToken provides a mock function with given fields: userID, role
func (_m *MockTokenGenerator) Generate(userID uuid.UUID, role string) (string, error) {
	ret := _m.Called(userID, role)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, string) (string, error)); ok {
		return rf(userID, role)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, string) string); ok {
		r0 = rf(userID, role)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, string) error); ok {
		r1 = rf(userID, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenGenerator_GenerateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockTokenGenerator_GenerateToken_Call struct {
	*mock.Call
}

// GenerateToken is a helper method to define mock.On call
//   - userID uuid.UUID
//   - role string
func (_e *MockTokenGenerator_Expecter) GenerateToken(userID interface{}, role interface{}) *MockTokenGenerator_GenerateToken_Call {
	return &MockTokenGenerator_GenerateToken_Call{Call: _e.mock.On("Generate", userID, role)}
}

func (_c *MockTokenGenerator_GenerateToken_Call) Run(run func(userID uuid.UUID, role string)) *MockTokenGenerator_GenerateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(string))
	})
	return _c
}

func (_c *MockTokenGenerator_GenerateToken_Call) Return(_a0 string, _a1 error) *MockTokenGenerator_GenerateToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenGenerator_GenerateToken_Call) RunAndReturn(run func(uuid.UUID, string) (string, error)) *MockTokenGenerator_GenerateToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateToken provides a mock function with given fields: token
func (_m *MockTokenGenerator) Validate(token string) (uuid.UUID, string, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 uuid.UUID
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (uuid.UUID, string, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) uuid.UUID); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(string) string); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(token)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockTokenGenerator_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockTokenGenerator_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - token string
func (_e *MockTokenGenerator_Expecter) ValidateToken(token interface{}) *MockTokenGenerator_ValidateToken_Call {
	return &MockTokenGenerator_ValidateToken_Call{Call: _e.mock.On("Validate", token)}
}

func (_c *MockTokenGenerator_ValidateToken_Call) Run(run func(token string)) *MockTokenGenerator_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTokenGenerator_ValidateToken_Call) Return(_a0 uuid.UUID, _a1 string, _a2 error) *MockTokenGenerator_ValidateToken_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockTokenGenerator_ValidateToken_Call) RunAndReturn(run func(string) (uuid.UUID, string, error)) *MockTokenGenerator_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenGenerator creates a new instance of MockTokenGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenGenerator {
	mock := &MockTokenGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
